# Generated by Django 3.2.11 on 2022-02-20 14:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 20, 14, 34, 37, 252710, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='profile',
            name='payment_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 20, 14, 34, 37, 252710, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriptions', models.CharField(choices=[('50000', 'یک ماهه'), ('100000', 'سه ماهه'), ('200000', 'شش ماهه'), ('500000', 'یک ساله')], default='50000', max_length=200, verbose_name='buy')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان تراکنش')),
                ('verify', models.BooleanField(default=False, verbose_name='نتیجه تراکنش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پرداخت ها',
                'verbose_name_plural': 'پرداخت ها',
            },
        ),
    ]
