# Generated by Django 3.2.11 on 2022-02-20 14:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220220_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 20, 14, 37, 12, 895851, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='payment_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 20, 14, 37, 12, 895851, tzinfo=utc)),
        ),
    ]
