# Generated by Django 3.2.11 on 2022-01-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='paid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
