# Generated by Django 3.2.11 on 2022-02-02 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_paid_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='paid_until',
        ),
    ]
