# Generated by Django 3.2.11 on 2022-02-20 15:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220220_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 20, 15, 12, 28, 88610, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='payment_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 20, 15, 12, 28, 88610, tzinfo=utc), null=True),
        ),
    ]
