# Generated by Django 3.2.11 on 2022-02-21 00:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220221_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 21, 0, 18, 11, 207897, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='payment_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 21, 0, 18, 11, 207897, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscriptions',
            field=models.IntegerField(choices=[('50000', 'یک ماهه'), ('100000', 'سه ماهه'), ('200000', 'شش ماهه'), ('500000', 'یک ساله')], default='50000', max_length=200, verbose_name='buy'),
        ),
    ]
