# Generated by Django 3.2.11 on 2022-02-21 00:46

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220221_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='expire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 21, 0, 45, 58, 477509, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='payment_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 21, 0, 45, 58, 477509, tzinfo=utc), null=True),
        ),
    ]
