# Generated by Django 3.2.11 on 2022-02-08 07:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPlaylist',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, default='profiles/user-defualt.png', null=True, upload_to='adminplaylists/')),
                ('pishnahadi_single', models.BooleanField(blank=True, default=False)),
                ('pishnahadi_homepage', models.BooleanField(blank=True, default=False)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'پلی\u200cلیست ادمین\u200c',
                'verbose_name_plural': 'پلی\u200cلیست ادمین\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('name', models.CharField(max_length=2000)),
                ('image', models.ImageField(upload_to='album_images/')),
                ('pishnahadi_single', models.BooleanField(blank=True, default=False)),
                ('pishnahadi_homepage', models.BooleanField(blank=True, default=False)),
                ('tarikh_enteshar', models.CharField(blank=True, max_length=20, null=True)),
                ('total_vote', models.IntegerField(blank=True, default=0, null=True)),
                ('vote_ratio', models.IntegerField(blank=True, default=0, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'آلبوم',
                'verbose_name_plural': 'آلبوم ها',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=190)),
                ('category_image', models.ImageField(blank=True, default='profiles/user-defualt.png', null=True, upload_to='category/')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'کتگوری',
                'verbose_name_plural': 'کتگوری ها',
            },
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('name', models.CharField(max_length=290)),
                ('singer_image', models.ImageField(blank=True, default='profiles/user-defualt.png', null=True, upload_to='singers/')),
                ('birthday', models.CharField(blank=True, max_length=11, null=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('pishnahadi_single', models.BooleanField(blank=True, default=False)),
                ('pishnahadi_homepage', models.BooleanField(blank=True, default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'خواننده',
                'verbose_name_plural': 'خواننده ها',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ ها',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('name', models.CharField(max_length=2000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='song_images/')),
                ('song128', models.FileField(upload_to='musics/')),
                ('song320', models.FileField(upload_to='musics/')),
                ('songfacp', models.FileField(upload_to='musics/')),
                ('tarikh_enteshar', models.CharField(blank=True, max_length=20, null=True)),
                ('total_vote', models.IntegerField(blank=True, default=0, null=True)),
                ('vote_ratio', models.IntegerField(blank=True, default=0, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='musicbeats.album')),
                ('category', models.ManyToManyField(blank=True, to='musicbeats.Category')),
                ('singer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='musicbeats.singer')),
                ('tags', models.ManyToManyField(blank=True, to='musicbeats.Tag')),
            ],
            options={
                'verbose_name': 'آهنگ',
                'verbose_name_plural': 'آهنگ ها',
                'ordering': ['total_vote'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('list_name', models.CharField(blank=True, max_length=100, null=True)),
                ('playlist_image', models.ImageField(blank=True, default='profiles/user-defualt.png', null=True, upload_to='playlist/')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('songs', models.ManyToManyField(blank=True, to='musicbeats.Song')),
            ],
            options={
                'verbose_name': 'پلی لیست',
                'verbose_name_plural': 'پلی لیست ها',
            },
        ),
        migrations.CreateModel(
            name='Hesohal',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('hesohal_image', models.ImageField(blank=True, default='profiles/user-defualt.png', null=True, upload_to='hesohal/')),
                ('pishnahadi_single', models.BooleanField(blank=True, default=False)),
                ('pishnahadi_homepage', models.BooleanField(blank=True, default=False)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('album', models.ManyToManyField(blank=True, to='musicbeats.Album')),
                ('playlist', models.ManyToManyField(blank=True, to='musicbeats.AdminPlaylist')),
                ('song', models.ManyToManyField(blank=True, to='musicbeats.Song')),
                ('tags', models.ManyToManyField(blank=True, to='musicbeats.Tag')),
            ],
            options={
                'verbose_name': 'حس و حال',
                'verbose_name_plural': 'حس و حال ها',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='category',
            field=models.ManyToManyField(blank=True, to='musicbeats.Category'),
        ),
        migrations.AddField(
            model_name='album',
            name='singer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='musicbeats.singer'),
        ),
        migrations.AddField(
            model_name='album',
            name='tags',
            field=models.ManyToManyField(blank=True, to='musicbeats.Tag'),
        ),
        migrations.AddField(
            model_name='adminplaylist',
            name='album',
            field=models.ManyToManyField(blank=True, to='musicbeats.Album'),
        ),
        migrations.AddField(
            model_name='adminplaylist',
            name='song',
            field=models.ManyToManyField(blank=True, to='musicbeats.Song'),
        ),
        migrations.AddField(
            model_name='adminplaylist',
            name='tags',
            field=models.ManyToManyField(blank=True, to='musicbeats.Tag'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('body', models.TextField(blank=True, null=True)),
                ('value', models.CharField(choices=[('up', 'up vote'), ('down', 'down vote')], max_length=200)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicbeats.song')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
                'ordering': ['create'],
                'unique_together': {('owner', 'song')},
            },
        ),
    ]
