# Generated by Django 4.0.1 on 2022-01-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0003_category_song_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='category',
            field=models.ManyToManyField(blank=True, to='musicbeats.Category'),
        ),
    ]
