# Generated by Django 4.0.1 on 2022-01-16 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0004_album_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musicbeats.song'),
        ),
    ]
