# Generated by Django 4.0.1 on 2022-01-17 06:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('musicbeats', '0006_rename_song_song_song128_song_song320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=190),
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('list_name', models.CharField(blank=True, max_length=100, null=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('songs', models.ManyToManyField(blank=True, to='musicbeats.Song')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
