# Generated by Django 4.0.1 on 2022-01-17 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0008_remove_song_singer_singer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singer',
            name='song',
        ),
        migrations.AddField(
            model_name='song',
            name='singer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='musicbeats.singer'),
        ),
        migrations.AddField(
            model_name='song',
            name='songfacp',
            field=models.FileField(default=1, upload_to='musics/'),
            preserve_default=False,
        ),
    ]
