# Generated by Django 4.0.1 on 2022-01-17 12:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0009_remove_singer_song_song_singer_song_songfacp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hesohal',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='musicbeats.album')),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='musicbeats.song')),
            ],
        ),
    ]
