# Generated by Django 4.0.1 on 2022-01-17 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0010_hesohal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='song',
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='musicbeats.album'),
        ),
    ]
