# Generated by Django 4.0.1 on 2022-01-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0012_remove_hesohal_album_hesohal_album_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='singer_image',
            field=models.ImageField(blank=True, default='profiles/user-defualt.png', null=True, upload_to='singers/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(upload_to='album_images/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='song_images/'),
        ),
    ]
