# Generated by Django 4.0.1 on 2022-01-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0017_category_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlist_image',
            field=models.ImageField(blank=True, default='profiles/user-defualt.png', null=True, upload_to='playlist/'),
        ),
    ]
