# Generated by Django 4.0.1 on 2022-01-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0018_playlist_playlist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='birthday',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
