# Generated by Django 4.0.1 on 2022-01-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0019_singer_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hesohal',
            name='album',
        ),
        migrations.RemoveField(
            model_name='hesohal',
            name='song',
        ),
        migrations.AddField(
            model_name='song',
            name='hesohal',
            field=models.ManyToManyField(blank=True, to='musicbeats.Hesohal'),
        ),
    ]
